In [2]:
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 14 14:35:17 2019

@author: anil kumar
"""
"""
import numpy as np
from scipy import stats
scores=np.array([109.4,76.2,128.7,93.7,85.6,117.7,117.2,87.3,100.3,55.1])
t=(110-np.mean(scores))/(stats.sem(scores))
td=stats.t(len(scores)-1)
p=2*td.sf(t)
print('tva1',t)
print('p',p)
"""
"""
import numpy as np
from scipy import stats
onesampledata=[177.3,182.7,169.6,176.3,180.3,179.4,178.5,177.2,181.8,176.5]
t,p_val=stats.ttest_1samp(onesampledata,177)
print("t-statstic:",t)
print("the p-value is:",p_val)"""
import pandas as pd
import numpy as np
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
data=np.random.rand(1000,2)
df = pd.DataFrame(data, columns=['value', 'treatment'])
model = ols('value ~ C(treatment)', df).fit()
anovaResults = anova_lm(model)
print(anovaResults)
print('anil')

                 df        sum_sq   mean_sq    F  PR(>F)
C(treatment)  999.0  8.497704e+01  0.085062  0.0     NaN
Residual        0.0  4.357868e-27       inf  NaN     NaN

In [3]:
%hist

# -*- coding: utf-8 -*-
"""
Created on Thu Mar 14 14:35:17 2019

@author: anil kumar
"""
"""
import numpy as np
from scipy import stats
scores=np.array([109.4,76.2,128.7,93.7,85.6,117.7,117.2,87.3,100.3,55.1])
t=(110-np.mean(scores))/(stats.sem(scores))
td=stats.t(len(scores)-1)
p=2*td.sf(t)
print('tva1',t)
print('p',p)
"""
"""
import numpy as np
from scipy import stats
onesampledata=[177.3,182.7,169.6,176.3,180.3,179.4,178.5,177.2,181.8,176.5]
t,p_val=stats.ttest_1samp(onesampledata,177)
print("t-statstic:",t)
print("the p-value is:",p_val)"""
import pandas as pd
import numpy as np
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
data=np.random.rand(1000,2)
df = pd.DataFrame(data, columns=['value', 'treatment'])
model = ols('value ~ C(treatment)', df).fit()
anovaResults = anova_lm(model)
print(anovaResults)
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 14 14:35:17 2019

@author: anil kumar
"""
"""
import numpy as np
from scipy import stats
scores=np.array([109.4,76.2,128.7,93.7,85.6,117.7,117.2,87.3,100.3,55.1])
t=(110-np.mean(scores))/(stats.sem(scores))
td=stats.t(len(scores)-1)
p=2*td.sf(t)
print('tva1',t)
print('p',p)
"""
"""
import numpy as np
from scipy import stats
onesampledata=[177.3,182.7,169.6,176.3,180.3,179.4,178.5,177.2,181.8,176.5]
t,p_val=stats.ttest_1samp(onesampledata,177)
print("t-statstic:",t)
print("the p-value is:",p_val)"""
import pandas as pd
import numpy as np
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
data=np.random.rand(1000,2)
df = pd.DataFrame(data, columns=['value', 'treatment'])
model = ols('value ~ C(treatment)', df).fit()
anovaResults = anova_lm(model)
print(anovaResults)
%hist

In [5]:
import numpy as np
import matplotlib.pyplot as plt

 # Generate the time-values
t = np.r_[0:10:0.1]
15
16 # Set the frequency, and calculate the sine-value
freq = 0.5
x = np.sin(2*np.pi*freq*t)
20 # Plot the data
plt.plot(t,x)
22
23 # Format the plot
plt.xlabel('Time[sec]')
plt.ylabel('Values')

27 # Generate a figure, one directory up
plt.savefig(r'..\Sinewave.png', dpi=200)

30 # Put it on the screen
plt.show()

In [7]:
import os
os.path.abspath(os.curdir)

'C:\\Users\\anil kumar\\Desktop\\programs\\python'

In [8]:
os.path.abspath(os.curdir)

'C:\\Users\\anil kumar\\Desktop\\programs\\python'

In [9]:
import numpy as np
import pandas as pd
t = np.arange(0,10,0.1)
x = np.sin(t)
y = np.cos(t)
df = pd.DataFrame({'Time':t, 'x':x, 'y':y})

In [10]:
df

    Time         x         y
0    0.0  0.000000  1.000000
1    0.1  0.099833  0.995004
2    0.2  0.198669  0.980067
3    0.3  0.295520  0.955336
4    0.4  0.389418  0.921061
5    0.5  0.479426  0.877583
6    0.6  0.564642  0.825336
7    0.7  0.644218  0.764842
8    0.8  0.717356  0.696707
9    0.9  0.783327  0.621610
10   1.0  0.841471  0.540302
11   1.1  0.891207  0.453596
12   1.2  0.932039  0.362358
13   1.3  0.963558  0.267499
14   1.4  0.985450  0.169967
15   1.5  0.997495  0.070737
16   1.6  0.999574 -0.029200
17   1.7  0.991665 -0.128844
18   1.8  0.973848 -0.227202
19   1.9  0.946300 -0.323290
20   2.0  0.909297 -0.416147
21   2.1  0.863209 -0.504846
22   2.2  0.808496 -0.588501
23   2.3  0.745705 -0.666276
24   2.4  0.675463 -0.737394
25   2.5  0.598472 -0.801144
26   2.6  0.515501 -0.856889
27   2.7  0.427380 -0.904072
28   2.8  0.334988 -0.942222
29   2.9  0.239249 -0.970958
..   ...       ...       ...
70   7.0  0.656987  0.753902
71   7.1  0.728969  0.684547
72   7.2  0.793668  0.608351
73   7.3  0.850437  0.526078
74   7.4  0.898708  0.438547
75   7.5  0.938000  0.346635
76   7.6  0.967920  0.251260
77   7.7  0.988168  0.153374
78   7.8  0.998543  0.053955
79   7.9  0.998941 -0.046002
80   8.0  0.989358 -0.145500
81   8.1  0.969890 -0.243544
82   8.2  0.940731 -0.339155
83   8.3  0.902172 -0.431377
84   8.4  0.854599 -0.519289
85   8.5  0.798487 -0.602012
86   8.6  0.734397 -0.678720
87   8.7  0.662969 -0.748647
88   8.8  0.584917 -0.811093
89   8.9  0.501021 -0.865435
90   9.0  0.412118 -0.911130
91   9.1  0.319098 -0.947722
92   9.2  0.222890 -0.974844
93   9.3  0.124454 -0.992225
94   9.4  0.024775 -0.999693
95   9.5 -0.075151 -0.997172
96   9.6 -0.174327 -0.984688
97   9.7 -0.271761 -0.962365
98   9.8 -0.366479 -0.930426
99   9.9 -0.457536 -0.889191

[100 rows x 3 columns]

In [11]:
df[['Time', 'y']][4:10]

   Time         y
4   0.4  0.921061
5   0.5  0.877583
6   0.6  0.825336
7   0.7  0.764842
8   0.8  0.696707
9   0.9  0.621610

In [12]:
df.iloc[4:10, [0,2]]

   Time         y
4   0.4  0.921061
5   0.5  0.877583
6   0.6  0.825336
7   0.7  0.764842
8   0.8  0.696707
9   0.9  0.621610

In [16]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve multiple elements
print (['a','c','d'])

['a', 'c', 'd']